export enum ErrorCodes {
  BAD_REQUEST = 'BAD_REQUEST',
  INVALID_API_SPEC_FORMAT = 'INVALID_API_SPEC_FORMAT',
  ENDPOINT_NOT_DEFINED_IN_API_SPEC = 'ENDPOINT_NOT_DEFINED_IN_API_SPEC',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}
